{{- if and .Values.sink .Values.sink.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.sink.secretName is required!" .Values.sink.secretName }}
stringData:
  {{- if eq .Values.sink.type "alertmanager" }}
  endpoint: {{ required ".Values.sink.endpoint is required!" .Values.sink.endpoint }}
  username: {{ .Values.sink.username }}
  password: {{ .Values.sink.password }}
  insecureSkipVerify: {{ .Values.sink.insecureSkipVerify }}
  caCert: |
{{ .Values.sink.caCert | indent 4 }}
  {{- else if eq .Values.sink.type "slack" }}
  apiToken: {{ required ".Values.sink.apiToken is required!" .Values.sink.apiToken }}
  channelId: {{ required ".Values.sink.channelId is required!" .Values.sink.channelId }}
  {{- end }}
{{- end }}