# permissions for end users to edit awsvalidators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsvalidator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: valid8or
    app.kubernetes.io/part-of: valid8or
    app.kubernetes.io/managed-by: kustomize
  name: awsvalidator-editor-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - awsvalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - awsvalidators/status
  verbs:
  - get
