apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - valid8orconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - valid8orconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - valid8orconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - validationresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - validationresults/finalizers
  verbs:
  - update
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - validationresults/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: valid8or
    app.kubernetes.io/part-of: valid8or
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'