apiVersion: v2
name: valid8or
description: valid8or monitors ValidationResults created by one or more valid8or plugins and uploads them to a configurable sink
type: application
version: 0.0.4 # x-release-please-version
appVersion: "0.0.4" # x-release-please-version
