apiVersion: v2
name: validator
description: Monitor results created by validator plugins and upload them to a configurable sink
type: application
version: 0.0.12  # x-release-please-version
appVersion: "0.0.12"  # x-release-please-version
