name: GoVulnCheck

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: govulncheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  govulncheck-pr-scan:
    runs-on: [self-hosted, Linux, X64, validator]
    container:
      image: gcr.io/spectro-images-public/golang:1.22-alpine
    steps:
      - name: install-govulncheck
        run: GOBIN=/usr/local/bin go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: govulncheck-scan
        run: |
          go version
          govulncheck -mode source ./...